---
abstract: 'Low level wrapper around the U2F two factor athentication C library (server side)'
author:
  - 'Rene Schickbauer <cavac@(none)>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-U2F
no_index:
  directory:
    - t
    - inc
requires: {}
version: '0.10'
